### ISSUE TITLE
6Poc/Citizen merge

### ISSUE THREAD

**Issue by SergeBredin** [anthill/6element#104]
# Goal

Merge is considered complete if we have one webpage with 6Poc where, when clicking on a recycling center, Roxane's RC tab shows up.

# Tasks 

- [x] merge client-side code
- [x] merge build processes (Citizen doesn't have JSX)
- [x] merge servers
- [x] move relevant pieces to Citizen and remove 6poc directory
